name: NodeJs test workflow

on:
  workflow_call:
    secrets:
      npmPkgToken:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Get branche name
        uses: EthanSK/git-branch-name-action@v1

      - name: Check branche name
        run: |
          if [[ $GIT_BRANCH_NAME =~ .*feat/* ]] || [[ $GIT_BRANCH_NAME =~ .*bugfix/* ]] || [[ $GIT_BRANCH_NAME =~ .*hotfix/* ]]
          then
            echo "The branche name is correct"
          else
            echo "The branche name is wrong"
            exit 1
          fi

      - name: Install NPM dependencies
        run: |
          npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npmPkgToken }}

      - name: Run unit tests
        run: |
          npm run test:ci

      - name: Test app building
        run: |
          npm run build:ci

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          annotations: none
          test-script: npm run test:ci
