name: NodeJs publish workflow

on:
  workflow_call:
    secrets:
      publishToken:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: https://npm.pkg.github.com
          cache: "npm"

      - name: Install NPM dependencies
        run: |
          npm ci

      - name: Build package
        run: |
          CI= npm run build:ci

      - name: Switch to main branch
        run: |
          git config --global user.email "GITHUB CI"
          git config --global user.name "GITHUB CI"
          git config --global pull.rebase true
          git fetch
          git checkout main

      - name: Publish package
        run: |
          npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.publishToken}}
