name: NodeJs versioning workflow

on:
  workflow_call:
    inputs:
      ownerName:
        required: true
        type: string
      repoName:
        required: true
        type: string
    secrets:
      repoAccessToken:
        required: true

jobs:
  versioning:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install NPM dependencies
        run: |
          npm ci

      - name: Get branche name
        uses: EthanSK/git-branch-name-action@v1

      - name: Update package version
        run: |
          if [[ $GIT_BRANCH_NAME =~ .*feat* ]]
          then
            echo "update minor version"
            npm version minor --git-tag-version=false
          elif [[ $GIT_BRANCH_NAME =~ .*fix* ]]
          then
            echo "update patch version"
            npm version patch --git-tag-version=false
          elif [[ $GIT_BRANCH_NAME =~ .*major* ]]
          then
            echo "update major version"
            npm version major --git-tag-version=false
          else
            echo "The branche name is wrong"
            exit 1
          fi

      - name: Create and push versioning branche
        run: |
          git config --global user.email "GITHUB CI"
          git config --global user.name "GITHUB CI"
          git config --global pull.rebase true
          git add .
          git commit -m "ci: update version"
          git checkout -b ci-bot-branche
          git fetch
          git checkout main
          git checkout ci-bot-branche
          git rebase main
          git push origin ci-bot-branche --force

      - name: Merge versioning branche
        run: |
          curl \
            -i \
            -u obenyahya:${{secrets.repoAccessToken}} \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{inputs.ownerName}}/${{inputs.repoName}}/merges \
            -d '{"base":"main","head":"ci-bot-branche"}'
